apiVersion: platform.confluent.io/v1beta1
kind: SchemaExporter
metadata:
  name: schema-exporter
  namespace: source
spec:
  sourceCluster:
    schemaRegistryClusterRef:
      name: schemaregistry
      namespace: source
#    schemaRegistryRest:
#      endpoint: http://localhost:8081
#      authentication:
#        type: basic
#        basic:
#          secretRef: rest-credential
  destinationCluster:
    schemaRegistryClusterRef:
      name: schemaregistry
      namespace: destination
  contextName: mycustom