---
# rolebinding `user-rb` allows group `/g1` to see kafkaCluster
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: user-rb
  namespace: confluent
spec:
  principal:
    type: group
    name: /g1
  role: ClusterAdmin
  ## if use other kafkaRestClass except for default, need to configure accordingly
  #kafkaRestClassRef:
  # name: default
---
# rolebinding `user-rb-sr` allows group `/g1` to see schemaregistry information
# `schemaRegistryCllusterId` pattern: `id_<schemaregistry.name>_<namespace>`
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: user-rb-sr
  namespace: confluent
spec:
  # The Schema Registry cluster is named `schemaregistry` and is deployed in the
  # namespace `confluent`
  # The Schema Registry cluster id naming pattern is: id_<sr-cluster-name>_<namespace>
  clustersScopeByIds:
    schemaRegistryClusterId: id_schemaregistry_confluent
  principal:
    name: /g1
    type: group
  role: SystemAdmin
---
# rolebinding `user-rb-connect` allows group `/g1` to see connect cluster
# `connectClusterId` pattern: `<namespace>.<connect.name>`
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: user-rb-connect
  namespace: confluent
spec:
  principal:
    type: group
    name: /g1
  clustersScopeByIds:
    connectClusterId: confluent.connect
  role: SystemAdmin
