---
# rolebinding `testuser-rb` allows `testuser1` to see kafkaCluster
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: testuser-rb
  namespace: confluent
spec:
  principal:
    type: user
    name: testuser1
  role: ClusterAdmin
  ## if use other kafkaRestClass except for default, need to configure accordingly
  #kafkaRestClassRef:
  # name: default
---
# rolebinding `testuser-rb-sr` allows `testuser1` to see schemaregistry information
# `schemaRegistryCllusterId` pattern: `id_<schemaregistry.name>_<namespace>`
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: testuser-rb-sr
  namespace: confluent
spec:
  # The Schema Registry cluster is named `schemaregistry` and is deployed in the
  # namespace `confluent`
  # The Schema Registry cluster id naming pattern is: id_<sr-cluster-name>_<namespace>
  clustersScopeByIds:
    schemaRegistryClusterId: id_schemaregistry_confluent
  principal:
    name: testuser1
    type: user
  role: SystemAdmin
---
# rolebinding `testuser-rb-connect` allows `testuser1` to see connect cluster
# `connectClusterId` pattern: `<namespace>.<connect.name>`
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: testuser-rb-connect
  namespace: confluent
spec:
  principal:
    type: user
    name: testuser1
  clustersScopeByIds:
    connectClusterId: confluent.connect
  role: SystemAdmin
---
# rolebinding `testuser-rb-ksql` allows `testuser1` to see ksql cluster
# `ksqlClusterId` pattern: `<namespace>.<ksql_cluster_name>`
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: testuser-rb-ksql
  namespace: confluent
spec:
  principal:
    type: user
    name: testuser1
  clustersScopeByIds:
    ksqlClusterId: confluent.ksqldb_
  role: SystemAdmin
