global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Gateway metrics scraping
  - job_name: 'gateway'
    static_configs:
      - targets: ['host.docker.internal:9190'] # gateway pods
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s
    scheme: http
    honor_labels: true
    honor_timestamps: true