apiVersion: v1
kind: ConfigMap
metadata:
  name: address-schema-config
  namespace: confluent
data:
  schema: |
    {
      "namespace": "com.example",
      "type": "record",
      "name": "Address",
      "fields": [
        {"name": "street", "type": "string"},
        {"name": "street2", "type": ["null","double"], "default":null},
        {"name": "city", "type": "string"},
        {"name": "pincode", "type":"int", "default":null}
      ]
    }