apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: oracle-xstream-cdc-source
  namespace: confluent
  labels:
    app: oracle-xstream-cdc
    connector-type: source
spec:
  name: oracle-xstream-cdc-source
  taskMax: 1
  class: io.confluent.connect.oracle.xstream.cdc.OracleXStreamSourceConnector
  configs:
    # Oracle Database Connection (Oracle 21c Enterprise Edition)
    database.hostname: "oracle-db.oracle.svc.cluster.local"
    database.port: "1521"
    database.user: "C##CFLTUSER"
    database.password: "password"
    database.dbname: "ORCLCDB"
    database.service.name: "ORCLCDB"
    database.pdb.name: "ORCLPDB1"
    
    # XStream Configuration  
    database.out.server.name: "XOUT"
    
    # Table Selection
    table.include.list: "SAMPLE.EMPLOYEES"
    
    # Topic Configuration
    topic.prefix: "ORCLPDB1"
    topic.creation.default.replication.factor: "3"
    topic.creation.default.partitions: "3"
    
    # Output Data Format
    key.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    key.converter.schema.registry.url: "http://schemaregistry.confluent.svc.cluster.local:8081"
    value.converter.schema.registry.url: "http://schemaregistry.confluent.svc.cluster.local:8081"
    
    # Schema History
    schema.history.internal.kafka.topic: "__orclpdb1-schema-changes.cflt"
    schema.history.internal.kafka.bootstrap.servers: "kafka.confluent.svc.cluster.local:9071"
    
  restartPolicy:
    type: "OnFailure"
    maxRetry: 5
    
  connectClusterRef:
    name: connect
    namespace: confluent