apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  annotations:
    platform.confluent.io/zookeeper-myid-offset: "10"
  name: zookeeper
  namespace: east
spec:
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: platformops.dev.gcp.devel.cpdev.cloud
      advertisedURL:
        enabled: true
        prefix: zk-east
      prefix: zk-east
  authentication:
    jaasConfig:
      secretRef: credential
    type: digest
  peers:
    - server.0=zk-central0.platformops.dev.gcp.devel.cpdev.cloud:2888:3888
    - server.10=zookeeper-0.zookeeper.east.svc.cluster.local:2888:3888
    - server.11=zookeeper-1.zookeeper.east.svc.cluster.local:2888:3888
    - server.20=zk-west0.platformops.dev.gcp.devel.cpdev.cloud:2888:3888
    - server.21=zk-west1.platformops.dev.gcp.devel.cpdev.cloud:2888:3888
  dataVolumeCapacity: 10Gi
  image:
    application: confluentinc/cp-zookeeper:7.5.0
    init: confluentinc/confluent-init-container:2.7.0
  logVolumeCapacity: 10Gi
  replicas: 2
  tls:
    autoGeneratedCerts: true
