apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  annotations:
    platform.confluent.io/disable-internal-rolebindings-creation: "true"
spec:
  replicas: 2
  image:
    application: confluentinc/cp-server-connect:7.0.1
    init: confluentinc/confluent-init-container:2.2.0-1
  tls:
    directoryPathInContainer: /vault/secrets
  license:
    directoryPathInContainer: /vault/secrets
  authorization:
    type: rbac
  podTemplate:
    serviceAccountName: confluent-sa
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/agent-inject-status: update
      vault.hashicorp.com/preserve-secret-case: "true"
      vault.hashicorp.com/agent-inject-secret-jksPassword.txt: secret/jksPassword.txt
      vault.hashicorp.com/agent-inject-template-jksPassword.txt: |
        {{- with secret "secret/jksPassword.txt" -}}
        {{ .Data.data.password }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-keystore.jks: secret/keystore.jks
      vault.hashicorp.com/agent-inject-template-keystore.jks: |
        {{- with secret "secret/keystore.jks" -}}
        {{ .Data.data.keystore | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-truststore.jks: secret/truststore.jks
      vault.hashicorp.com/agent-inject-template-truststore.jks: |
        {{- with secret "secret/truststore.jks" -}}
        {{ .Data.data.truststore | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-connect-bearer: secret/connect/bearer.txt
      vault.hashicorp.com/agent-inject-file-connect-bearer: bearer.txt # this are mandatory name
      vault.hashicorp.com/agent-inject-template-connect-bearer: |
        {{- with secret "secret/connect/bearer.txt" -}}
        {{ .Data.data.bearer | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-kafka-client-sasl-plain: secret/kafka-client/plain-jaas.conf
      vault.hashicorp.com/secret-volume-path-kafka-client-sasl-plain: /vault/secrets/jaas
      vault.hashicorp.com/agent-inject-file-kafka-client-sasl-plain: plain-jaas.conf # this are mandatory names
      vault.hashicorp.com/agent-inject-template-kafka-client-sasl-plain: |
        {{- with secret "secret/kafka-client/plain-jaas.conf" -}}
        {{ .Data.data.plainjaas | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-license: secret/license.txt
      vault.hashicorp.com/agent-inject-file-license: license.txt # this are mandatory names
      vault.hashicorp.com/agent-inject-template-license: |
        {{- with secret "secret/license.txt" -}}
        {{ .Data.data.license | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-mds-publickey: secret/mdsPublicKey.pem
      vault.hashicorp.com/agent-inject-file-mds-publickey: mdsPublicKey.pem # must be with this name
      vault.hashicorp.com/agent-inject-template-mds-publickey: |
        {{- with secret "secret/mdsPublicKey.pem" -}}
        {{ .Data.data.mdspublickey | base64Decode }}
        {{- end }}
      vault.hashicorp.com/role: confluent-operator
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      authentication:
        type: plain
        jaasConfigPassThrough:
          directoryPathInContainer: /vault/secrets/jaas
      tls:
        enabled: true
    schemaRegistry:
      url: https://schemaregistry.confluent.svc.cluster.local:8081
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.confluent.svc.cluster.local:8090
      tokenKeyPair:
        directoryPathInContainer: /vault/secrets
      authentication:
        type: bearer
        bearer:
          directoryPathInContainer: /vault/secrets
      tls:
        enabled: true
---
apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: ksqldb
  annotations:
    platform.confluent.io/disable-internal-rolebindings-creation: "true"
spec:
  replicas: 2
  image:
    application: confluentinc/cp-ksqldb-server:7.0.1
    init: confluentinc/confluent-init-container:2.2.0-1
  dataVolumeCapacity: 10Gi
  authorization:
    type: rbac
  tls:
    directoryPathInContainer: /vault/secrets
  license:
    directoryPathInContainer: /vault/secrets
  podTemplate:
    serviceAccountName: confluent-sa
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/agent-inject-status: update
      vault.hashicorp.com/preserve-secret-case: "true"
      vault.hashicorp.com/agent-inject-secret-jksPassword.txt: secret/jksPassword.txt
      vault.hashicorp.com/agent-inject-template-jksPassword.txt: |
        {{- with secret "secret/jksPassword.txt" -}}
        {{ .Data.data.password }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-keystore.jks: secret/keystore.jks
      vault.hashicorp.com/agent-inject-template-keystore.jks: |
        {{- with secret "secret/keystore.jks" -}}
        {{ .Data.data.keystore | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-truststore.jks: secret/truststore.jks
      vault.hashicorp.com/agent-inject-template-truststore.jks: |
        {{- with secret "secret/truststore.jks" -}}
        {{ .Data.data.truststore | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-ksqldb-bearer: secret/ksqldb/bearer.txt
      vault.hashicorp.com/agent-inject-file-ksqldb-bearer: bearer.txt # this are mandatory name
      vault.hashicorp.com/agent-inject-template-ksqldb-bearer: |
        {{- with secret "secret/ksqldb/bearer.txt" -}}
        {{ .Data.data.bearer | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-kafka-client-sasl-plain: secret/kafka-client/plain-jaas.conf
      vault.hashicorp.com/secret-volume-path-kafka-client-sasl-plain: /vault/secrets/jaas
      vault.hashicorp.com/agent-inject-file-kafka-client-sasl-plain: plain-jaas.conf # this are mandatory names
      vault.hashicorp.com/agent-inject-template-kafka-client-sasl-plain: |
        {{- with secret "secret/kafka-client/plain-jaas.conf" -}}
        {{ .Data.data.plainjaas | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-license: secret/license.txt
      vault.hashicorp.com/agent-inject-file-license: license.txt # this are mandatory names
      vault.hashicorp.com/agent-inject-template-license: |
        {{- with secret "secret/license.txt" -}}
        {{ .Data.data.license | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-mds-publickey: secret/mdsPublicKey.pem
      vault.hashicorp.com/agent-inject-file-mds-publickey: mdsPublicKey.pem # must be with this name
      vault.hashicorp.com/agent-inject-template-mds-publickey: |
        {{- with secret "secret/mdsPublicKey.pem" -}}
        {{ .Data.data.mdspublickey | base64Decode }}
        {{- end }}
      vault.hashicorp.com/role: confluent-operator
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      authentication:
        type: plain
        jaasConfigPassThrough:
          directoryPathInContainer: /vault/secrets/jaas
      tls:
        enabled: true
    schemaRegistry:
      url: https://schemaregistry.confluent.svc.cluster.local:8081
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.confluent.svc.cluster.local:8090
      tokenKeyPair:
        directoryPathInContainer: /vault/secrets
      authentication:
        type: bearer
        bearer:
          directoryPathInContainer: /vault/secrets
      tls:
        enabled: true
---
apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  annotations:
    platform.confluent.io/disable-internal-rolebindings-creation: "true"
spec:
  replicas: 2
  image:
    application: confluentinc/cp-schema-registry:7.0.1
    init: confluentinc/confluent-init-container:2.2.0-1
  tls:
    directoryPathInContainer: /vault/secrets
  license:
    directoryPathInContainer: /vault/secrets
  authorization:
    type: rbac
  podTemplate:
    serviceAccountName: confluent-sa
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/agent-inject-status: update
      vault.hashicorp.com/preserve-secret-case: "true"
      vault.hashicorp.com/agent-inject-secret-jksPassword.txt: secret/jksPassword.txt
      vault.hashicorp.com/agent-inject-template-jksPassword.txt: |
        {{- with secret "secret/jksPassword.txt" -}}
        {{ .Data.data.password }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-keystore.jks: secret/keystore.jks
      vault.hashicorp.com/agent-inject-template-keystore.jks: |
        {{- with secret "secret/keystore.jks" -}}
        {{ .Data.data.keystore | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-truststore.jks: secret/truststore.jks
      vault.hashicorp.com/agent-inject-template-truststore.jks: |
        {{- with secret "secret/truststore.jks" -}}
        {{ .Data.data.truststore | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-connect-bearer: secret/schemaregistry/bearer.txt
      vault.hashicorp.com/agent-inject-file-connect-bearer: bearer.txt # this are mandatory name
      vault.hashicorp.com/agent-inject-template-connect-bearer: |
        {{- with secret "secret/schemaregistry/bearer.txt" -}}
        {{ .Data.data.bearer | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-kafka-client-sasl-plain: secret/kafka-client/plain-jaas.conf
      vault.hashicorp.com/secret-volume-path-kafka-client-sasl-plain: /vault/secrets/jaas
      vault.hashicorp.com/agent-inject-file-kafka-client-sasl-plain: plain-jaas.conf # this are mandatory names
      vault.hashicorp.com/agent-inject-template-kafka-client-sasl-plain: |
        {{- with secret "secret/kafka-client/plain-jaas.conf" -}}
        {{ .Data.data.plainjaas | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-license: secret/license.txt
      vault.hashicorp.com/agent-inject-file-license: license.txt # this are mandatory names
      vault.hashicorp.com/agent-inject-template-license: |
        {{- with secret "secret/license.txt" -}}
        {{ .Data.data.license | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-mds-publickey: secret/mdsPublicKey.pem
      vault.hashicorp.com/agent-inject-file-mds-publickey: mdsPublicKey.pem # must be with this name
      vault.hashicorp.com/agent-inject-template-mds-publickey: |
        {{- with secret "secret/mdsPublicKey.pem" -}}
        {{ .Data.data.mdspublickey | base64Decode }}
        {{- end }}
      vault.hashicorp.com/role: confluent-operator
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      authentication:
        type: plain
        jaasConfigPassThrough:
          directoryPathInContainer: /vault/secrets/jaas
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.confluent.svc.cluster.local:8090
      tokenKeyPair:
        directoryPathInContainer: /vault/secrets
      authentication:
        type: bearer
        bearer:
          directoryPathInContainer: /vault/secrets
      tls:
        enabled: true
---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  annotations:
    platform.confluent.io/disable-internal-rolebindings-creation: "true"
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center:7.0.1
    init: confluentinc/confluent-init-container:2.2.0-1
  dataVolumeCapacity: 10Gi
  authorization:
    type: rbac
  tls:
    directoryPathInContainer: /vault/secrets
  license:
    directoryPathInContainer: /vault/secrets
  podTemplate:
    serviceAccountName: confluent-sa
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/agent-inject-status: update
      vault.hashicorp.com/preserve-secret-case: "true"
      vault.hashicorp.com/agent-inject-secret-jksPassword.txt: secret/jksPassword.txt
      vault.hashicorp.com/agent-inject-template-jksPassword.txt: |
        {{- with secret "secret/jksPassword.txt" -}}
        {{ .Data.data.password }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-keystore.jks: secret/keystore.jks
      vault.hashicorp.com/agent-inject-template-keystore.jks: |
        {{- with secret "secret/keystore.jks" -}}
        {{ .Data.data.keystore | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-truststore.jks: secret/truststore.jks
      vault.hashicorp.com/agent-inject-template-truststore.jks: |
        {{- with secret "secret/truststore.jks" -}}
        {{ .Data.data.truststore | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-controlcenter-bearer: secret/controlcenter/bearer.txt
      vault.hashicorp.com/agent-inject-file-controlcenter-bearer: bearer.txt # this are mandatory name
      vault.hashicorp.com/agent-inject-template-controlcenter-bearer: |
        {{- with secret "secret/controlcenter/bearer.txt" -}}
        {{ .Data.data.bearer | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-kafka-client-sasl-plain: secret/kafka-client/plain-jaas.conf
      vault.hashicorp.com/secret-volume-path-kafka-client-sasl-plain: /vault/secrets/jaas
      vault.hashicorp.com/agent-inject-file-kafka-client-sasl-plain: plain-jaas.conf # this are mandatory names
      vault.hashicorp.com/agent-inject-template-kafka-client-sasl-plain: |
        {{- with secret "secret/kafka-client/plain-jaas.conf" -}}
        {{ .Data.data.plainjaas | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-license: secret/license.txt
      vault.hashicorp.com/agent-inject-file-license: license.txt
      vault.hashicorp.com/agent-inject-template-license: |
        {{- with secret "secret/license.txt" -}}
        {{ .Data.data.license | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-mds-publickey: secret/mdsPublicKey.pem
      vault.hashicorp.com/agent-inject-file-mds-publickey: mdsPublicKey.pem # must be with this name
      vault.hashicorp.com/agent-inject-template-mds-publickey: |
        {{- with secret "secret/mdsPublicKey.pem" -}}
        {{ .Data.data.mdspublickey | base64Decode }}
        {{- end }}
      vault.hashicorp.com/role: confluent-operator
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      authentication:
        type: plain
        jaasConfigPassThrough:
          directoryPathInContainer: /vault/secrets/jaas
      tls:
        enabled: true
    schemaRegistry:
      url: https://schemaregistry.confluent.svc.cluster.local:8081
      tls:
        enabled: true
    ksqldb:
    - name: ksql
      url: https://ksqldb.confluent.svc.cluster.local:8088
      tls:
        enabled: true
    connect:
    - name: connect
      url:  https://connect.confluent.svc.cluster.local:8083
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.confluent.svc.cluster.local:8090
      tokenKeyPair:
        directoryPathInContainer: /vault/secrets
      authentication:
        type: bearer
        bearer:
          directoryPathInContainer: /vault/secrets
      tls:
        enabled: true