---
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: confluent
spec:
  replicas: 3
  image:
    application: confluentinc/cp-zookeeper:7.7.0
    init: confluentinc/confluent-init-container:2.9.0
  dataVolumeCapacity: 10Gi
  logVolumeCapacity: 10Gi
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  image:
    application: confluentinc/cp-server:7.7.0
    init: confluentinc/confluent-init-container:2.9.0
  dataVolumeCapacity: 10Gi
  listeners:
    external:
      authentication:
        type: ldap
  identityProvider:
    type: ldap
    ldap:
      address: ldaps://ldap.confluent.svc.cluster.local:636
      authentication:
        type: simple
        simple:
          secretRef: ldaps-user
      tls:
        enabled: true
        secretRef: ldaps-tls
      configurations:
        groupNameAttribute: cn
        groupObjectClass: group
        groupMemberAttribute: member
        groupMemberAttributePattern: CN=(.*),DC=test,DC=com
        groupSearchBase: dc=test,dc=com
        userNameAttribute: cn
        userMemberOfAttributePattern: CN=(.*),DC=test,DC=com
        userObjectClass: organizationalRole
        userSearchBase: dc=test,dc=com
  metricReporter:
    enabled: true
---
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-server-connect:7.7.0
    init: confluentinc/confluent-init-container:2.9.0
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
---
apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: ksqldb
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-ksqldb-server:7.7.0
    init: confluentinc/confluent-init-container:2.9.0
  dataVolumeCapacity: 10Gi
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  license:
    globalLicense: true
  configOverrides:
    jvm:
     - -Djavax.net.ssl.trustStore=/mnt/secrets/ldaps-tls/truststore.jks
     - -Djavax.net.ssl.trustStorePassword=mystorepassword
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center:7.7.0
    init: confluentinc/confluent-init-container:2.9.0
  dataVolumeCapacity: 10Gi
  mountedSecrets:
  - secretRef: ldaps-tls
  authentication:
    type: ldap
    ldap:
      secretRef: ldaps-user
      roles: [c3users,readonlyusers]
      restrictedRoles: [readonlyusers]
      property:
        useLdaps : "true" 
        debug: "true" 
        contextFactory: "com.sun.jndi.ldap.LdapCtxFactory"
        hostname: "ldap.confluent.svc.cluster.local"
        port: "636" 
        bindDn: ""
        bindPassword: ""
        authenticationMethod: "simple"
        forceBindingLogin: "false"
        userBaseDn: "ou=users,dc=test,dc=com"
        userObjectClass: "inetOrgPerson" 
        userRdnAttribute: "uid"
        userIdAttribute: "cn"
        roleBaseDn: "ou=groups,dc=test,dc=com"
        roleNameAttribute: "cn"
        roleMemberAttribute: "memberUid"
        roleObjectClass: "posixGroup" 
        userPasswordAttribute: "userPassword"
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
    ksqldb:
    - name: ksqldb
      url: http://ksqldb.confluent.svc.cluster.local:8088
    connect:
    - name: connect
      url: http://connect.confluent.svc.cluster.local:8083
---
apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-schema-registry:7.7.0
    init: confluentinc/confluent-init-container:2.9.0
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestProxy
metadata:
  name: kafkarestproxy
  namespace: confluent
spec:
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
  image:
    application: confluentinc/cp-kafka-rest:7.7.0
    init: confluentinc/confluent-init-container:2.9.0
  replicas: 1
