apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: central
spec:
  authorization:
    superUsers:
      - User:kafka
    type: rbac
  configOverrides:
    server:
      - client.rack=us-central1
      - confluent.license.topic.replication.factor=3
      - replica.selector.class=org.apache.kafka.common.replica.RackAwareReplicaSelector
  dataVolumeCapacity: 10Gi
  dependencies:
    kafkaRest:
      authentication:
        bearer:
          secretRef: mds-client
        type: bearer
    zookeeper:
      authentication:
        jaasConfig:
          secretRef: credential
        type: digest
      endpoint: zookeeper.central.svc.cluster.local:2182/mrc,zookeeper.east.svc.cluster.local:2182/mrc,zookeeper.west.svc.cluster.local:2182/mrc
      tls:
        enabled: true
  image:
    application: confluentinc/cp-server:7.5.0
    init: confluentinc/confluent-init-container:2.7.0
  listeners:
    external:
      authentication:
        jaasConfig:
          secretRef: credential
        type: plain
      externalAccess:
        loadBalancer:
          bootstrapPrefix: kafka.central
          brokerPrefix: kafka.central.broker
          domain: mydomain.com
        type: loadBalancer
      tls:
        enabled: true
    internal:
      authentication:
        jaasConfig:
          secretRef: credential
        type: plain
      tls:
        enabled: true
  podTemplate:
    serviceAccountName: kafka
  rackAssignment:
    nodeLabels:
      - topology.kubernetes.io/region
  replicas: 2
  services:
    mds:
      provider:
        ldap:
          address: ldap://ldap-0.ldap.central.svc.cluster.local:389
          authentication:
            simple:
              secretRef: credential
            type: simple
          configurations:
            groupNameAttribute: cn
            groupObjectClass: posixGroup
            groupMemberAttribute: memberuid
            groupMemberAttributePattern: cn=(.*),ou=users,dc=test,dc=com
            groupSearchBase: ou=groups,dc=test,dc=com
            userNameAttribute: cn
            userMemberOfAttributePattern: cn=(.*),ou=users,dc=test,dc=com
            userObjectClass: inetOrgPerson
            userSearchBase: ou=users,dc=test,dc=com
        type: ldap
      tls:
        enabled: true
      tokenKeyPair:
        secretRef: mds-token
  tls:
    autoGeneratedCerts: true