apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  annotations:
    platform.confluent.io/broker-id-offset: "10"
  name: kafka
  namespace: east
spec:
  authorization:
    superUsers:
      - User:kafka
    type: rbac
  configOverrides:
    server:
      - client.rack=us-east1
      - confluent.license.topic.replication.factor=3
      - replica.selector.class=org.apache.kafka.common.replica.RackAwareReplicaSelector
  dataVolumeCapacity: 10Gi
  dependencies:
    kafkaRest:
      authentication:
        bearer:
          secretRef: mds-client
        type: bearer
    zookeeper:
      authentication:
        jaasConfig:
          secretRef: credential
        type: digest
      endpoint: zookeeper.central.svc.cluster.local:2182,zookeeper.east.svc.cluster.local:2182,zookeeper.west.svc.cluster.local:2182/mrc
      tls:
        enabled: true
  image:
    application: confluentinc/cp-server:7.7.0
    init: confluentinc/confluent-init-container:2.9.0
  listeners:
    external:
      authentication:
        jaasConfig:
          secretRef: credential
        type: plain
      externalAccess:
        loadBalancer:
          bootstrapPrefix: kafka.east
          brokerPrefix: kafka.east.broker
          domain: mydomain.com
        type: loadBalancer
      tls:
        enabled: true
    internal:
      authentication:
        jaasConfig:
          secretRef: credential
        type: plain
      tls:
        enabled: true
  podTemplate:
    serviceAccountName: kafka
  rackAssignment:
    nodeLabels:
      - topology.kubernetes.io/region
  replicas: 2
  services:
    mds:
      provider:
        ldap:
          address: ldap://ldap-0.ldap.central.svc.cluster.local:389
          authentication:
            simple:
              secretRef: credential
            type: simple
          configurations:
            groupMemberAttribute: member
            groupMemberAttributePattern: CN=(.*),DC=test,DC=com
            groupNameAttribute: cn
            groupObjectClass: group
            groupSearchBase: dc=test,dc=com
            groupSearchScope: 1
            userMemberOfAttributePattern: CN=(.*),DC=test,DC=com
            userNameAttribute: cn
            userObjectClass: organizationalRole
            userSearchBase: dc=test,dc=com
            userSearchScope: 1
        type: ldap
      tls:
        enabled: true
      tokenKeyPair:
        secretRef: mds-token
  tls:
    autoGeneratedCerts: true