---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: pageviews
  namespace: confluent
spec:
  class: "io.confluent.kafka.connect.datagen.DatagenConnector"
  taskMax: 2
  connectClusterRef:
    name: connect
  configs:
    kafka.topic: "pageviews"
    quickstart: "pageviews"
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    key.converter.schemas.enable: "false"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schemas.enable: "true"
    value.converter.schema.registry.url: "http://schemaregistry.confluent.svc.cluster.local:8081"
    schema.registry.url: "http://schemaregistry.confluent.svc.cluster.local:8081"
    max.interval: "1000"
    iterations: "10000000000"

---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: pagevie
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 3
  configs:
    cleanup.policy: "delete"
---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: users
  namespace: confluent
spec:
  class: "io.confluent.kafka.connect.datagen.DatagenConnector"
  taskMax: 2
  connectClusterRef:
    name: connect
  configs:
    kafka.topic: "users"
    quickstart: "users"
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    key.converter.schemas.enable: "false"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schemas.enable: "true"
    value.converter.schema.registry.url: "http://schemaregistry.confluent.svc.cluster.local:8081"
    schema.registry.url: "http://schemaregistry.confluent.svc.cluster.local:8081"
    max.interval: "3000"
    iterations: "10000000"
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: users
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 3
  configs:
    cleanup.policy: "delete"