{
 "title": "Confluent Platform",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Hardware Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage by Host",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(rate(process_cpu_seconds_total[1m])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Heap)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(jvm_memory_bytes_used{ area=\"heap\"} / jvm_memory_bytes_max{ area=\"heap\"}) * 100",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "io_confluent_caas_volumemetrics_used{}",
     "legendFormat": "Used {{hostname }}"
    },
    {
     "expr": "io_confluent_caas_volumemetrics_total{}",
     "legendFormat": "Total {{hostname}}"
    }
   ]
  },
  {
   "title": "GC time spent",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(rate(jvm_gc_collection_seconds_sum[1m]) / rate(jvm_gc_collection_seconds_count[1m]))*100",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Disk Read Bytes (Linux only)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "kafka_server_kafkaserver_value{name=\"linux-disk-read-bytes\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Disk Available (Percentage)",
   "type": "graph",
   "description": "Kafka Broker Pods Disk Usage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "io_confluent_caas_volumemetrics_percentavailable{}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Disk Write Bytes (Linux only)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "kafka_server_kafkaserver_value{name=\"linux-disk-write-bytes\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Disk Usage (Percentage)",
   "type": "graph",
   "description": "Kafka Broker Pods Disk Usage",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "io_confluent_caas_volumemetrics_percentused{}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "description": "Number of Brokers Online",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_value{name=\"LeaderCount\"})\n"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(kafka_controller_kafkacontroller_value{name=\"ActiveControllerCount\"}))"
    }
   ]
  },
  {
   "title": "Under Min ISR Partition Count",
   "type": "stat",
   "description": "Number of partitions whose in-sync replicas count is less than minIsr.\n",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{name=~\"UnderMinIsrPartitionCount\"})"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate",
   "type": "stat",
   "description": "Unclean leader election rate",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_controllerstats_oneminuterate{name=~\"UncleanLeaderElectionsPerSec\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{name=~\"UnderReplicatedPartitions\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "stat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{name=~\"OfflineReplicaCount\"})"
    }
   ]
  },
  {
   "title": "Broker Online",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_value{name=\"LeaderCount\"})\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ActiveControllerCount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_value{name=\"ActiveControllerCount\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "UnderMinIsrPartitionCount ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 49 },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{name=~\"UnderMinIsrPartitionCount\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "UncleanLeaderElectionsPerSec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "kafka_controller_controllerstats_oneminuterate{name=\"UncleanLeaderElectionsPerSec\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "UnderReplicatedPartitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_value{name=\"UnderReplicatedPartitions\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "OfflineReplicaCount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 49 },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_value{name=\"OfflineReplicaCount\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Total Partition Count",
   "type": "stat",
   "description": "Partitions that are online",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{name=~\"PartitionCount\"})"
    }
   ]
  },
  {
   "title": "Total Topic Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_value{name=\"GlobalTopicCount\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Under Min ISR by Topic",
   "type": "barchart",
   "description": "Byte Rate to and from Kafka clients",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_cluster_partition_value{name=\"UnderMinIsr\"} > 0"
    }
   ]
  },
  {
   "title": "Partition Leader Count per Broker",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_value{name=~\"LeaderCount\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Partition Count per Broker",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_value{name=~\"PartitionCount\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Total Partition Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{name=~\"PartitionCount\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Total Topic Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 63 },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_value{name=\"GlobalTopicCount\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ReassigningPartitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 63 },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{name=\"ReassigningPartitions\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Messages In Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=\"MessagesInPerSec\"})",
     "legendFormat": "{{Messages In Per Second}}"
    }
   ]
  },
  {
   "title": "Byte Rate (Client)",
   "type": "graph",
   "description": "Byte Rate to and from Kafka clients",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesInPerSec\"})",
     "legendFormat": "Incoming Byte Rate"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesOutPerSec\"})",
     "legendFormat": "Outgoing Byte Rate"
    }
   ]
  },
  {
   "title": "Request Handler Idle",
   "type": "timeseries",
   "description": "Average fraction of time the request handler threads are idle. Values are between 0 (all resources are used) and 1 (all resources are available).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "kafka_server_kafkarequesthandlerpool_oneminuterate{name=~\"RequestHandlerAvgIdlePercent\"}*100\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Byte Rate (Replication)",
   "type": "graph",
   "description": "Byte Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=\"ReplicationBytesInPerSec\"})",
     "legendFormat": "Incoming Byte Rate"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=\"ReplicationBytesOutPerSec\"})",
     "legendFormat": "Outgoing Byte Rate"
    }
   ]
  },
  {
   "title": "Network Processor Avg Idle Percent",
   "type": "timeseries",
   "description": "Network Processor Avg Idle Percent",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "kafka_network_socketserver_value{name=~\"NetworkProcessorAvgIdlePercent\"}*100",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Byte Rate In (Replication) per Broker ",
   "type": "graph",
   "description": "Byte Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_oneminuterate{name=\"ReplicationBytesInPerSec\"}\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Produce Request Rate",
   "type": "graph",
   "description": "Produce Request Rate.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=\"TotalProduceRequestsPerSec\"})",
     "legendFormat": "Total Produce Request Rate"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=\"FailedProduceRequestsPerSec\"})",
     "legendFormat": "Failed Produce Request Rate"
    }
   ]
  },
  {
   "title": "Fetch Request Rate",
   "type": "graph",
   "description": "Fetch Request Rate",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=~\"TotalFetchRequestsPerSec\"})",
     "legendFormat": "Fetch Request Rate"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=~\"FailedFetchRequestsPerSec\"})",
     "legendFormat": "Failed Fetch Request Rate"
    }
   ]
  },
  {
   "title": "Byte Rate Out (Replication) per Broker ",
   "type": "graph",
   "description": "Byte Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_oneminuterate{name=\"ReplicationBytesOutPerSec\"}\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Confluent Zookeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Zookeepers Online",
   "type": "stat",
   "description": "Number of Zookeepers Online",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_sessionexpirelistener_count{name=\"ZooKeeperSyncConnectsPerSec\"})\n"
    }
   ]
  },
  {
   "title": "Zookeeper Disconnects",
   "type": "stat",
   "description": "Number of Alive Connections",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_sessionexpirelistener_count{name=\"ZooKeeperDisconnectsPerSec\"})"
    }
   ]
  },
  {
   "title": "ZK Expires per sec",
   "type": "stat",
   "description": "The ZooKeeper session has expired. When a session expires, we can have leader changes and even a new controller. It is important to keep an eye on the number of such events across a Kafka cluster and if the overall number is high, then we have a few recommendations:\n\nCheck the health of your network\nCheck for garbage collection issues and tune it accordingly\nIf necessary, increase the session time out by setting the value of zookeeper.session.timeout.ms.\n",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_sessionexpirelistener_count{name=~\"ZooKeeperExpiresPerSec\"})\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Avg Quorum Size per ZK",
   "type": "stat",
   "description": "Represents the Quorum, or Ensemble - parent of all cluster members. ",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg({__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_quorumsize\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Number of Watchers",
   "type": "stat",
   "description": "Number of Watchers",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_watchcount\"})"
    }
   ]
  },
  {
   "title": "Total Number of ZNodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_nodecount\"})\n"
    }
   ]
  },
  {
   "title": "Zookeepers Online",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "count(kafka_server_sessionexpirelistener_count{name=\"ZooKeeperSyncConnectsPerSec\"})\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Zookeeper disconnects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 108 },
   "targets": [
    {
     "expr": "sum(kafka_server_sessionexpirelistener_count{name=\"ZooKeeperDisconnectsPerSec\"})\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ZK Expires",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 108 },
   "targets": [
    {
     "expr": "sum(kafka_server_sessionexpirelistener_count{name=\"ZooKeeperExpiresPerSec\"})\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Avg Quorum Size ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 108 },
   "targets": [
    {
     "expr": "avg({__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_quorumsize\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_avgrequestlatency\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Disk Usage (txnlog)",
   "type": "graph",
   "description": "Zookeeper Disk Usage (txnlog)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"txnlog-$component_name.*\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "timeseries",
   "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_outstandingrequests\"}  ",
     "legendFormat": "{{kubernetes_pod_name}}-{{name2}}"
    }
   ]
  },
  {
   "title": "Request Latency (max)",
   "type": "timeseries",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_maxrequestlatency\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Confluent Connect",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Connectors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_count{})\n",
     "legendFormat": "{{ kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Number of Tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_task_count{})"
    }
   ]
  },
  {
   "title": "Connector Startup Failure Total",
   "type": "stat",
   "description": "The total number of connector starts that failed.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_startup_failure_total{})"
    }
   ]
  },
  {
   "title": "Task Startup Failure Total",
   "type": "stat",
   "description": "The total number of task starts that failed.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_task_startup_failure_total{})"
    }
   ]
  },
  {
   "title": "Running Ratio",
   "type": "stat",
   "description": "Fraction of time the task has spent in the running state\n",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kafka_connect_connector_task_metrics_running_ratio{}*100\n)"
    }
   ]
  },
  {
   "title": "Connector Startup Success Total",
   "type": "timeseries",
   "description": "The total number of connector starts that succeeded.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_startup_success_total{})"
    }
   ]
  },
  {
   "title": "Tasks Total",
   "type": "timeseries",
   "description": "Number of tasks that have run in this worker",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_task_count{})"
    }
   ]
  },
  {
   "title": "Connector Startup Failure Total",
   "type": "timeseries",
   "description": "The total number of connector starts that failed.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_startup_failure_total{})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Task startup failure total",
   "type": "timeseries",
   "description": "Total number of task starts that failed\n",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_task_startup_failure_total{})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Running State %",
   "type": "timeseries",
   "description": "Fraction of time the task has spent in the running state",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(connector) (kafka_connect_connector_task_metrics_running_ratio*100\n)",
     "legendFormat": "{{connector}} (avg)"
    }
   ]
  },
  {
   "title": "Connect Metrics: IO Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_io_ratio{}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Connect Metrics: Incoming Byte Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_incoming_byte_rate{}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Task Offset Commit Time (Avg/Max)",
   "type": "timeseries",
   "description": "1) Maximum time in milliseconds taken by the task to commit offsets\n2) Average time in milliseconds taken by the task to commit offsets",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(connector) (kafka_connect_connector_task_metrics_offset_commit_avg_time_ms)",
     "legendFormat": "{{connector}} (avg)"
    },
    {
     "expr": "max by(connector) (kafka_connect_connector_task_metrics_offset_commit_max_time_ms)",
     "legendFormat": "{{connector}} (max)"
    }
   ]
  },
  {
   "title": "Connect Metrics: Network IO Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_network_io_rate{}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Connect Metrics: Outgoing Byte Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_outgoing_byte_rate{}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Offset Commit Success (Avg)",
   "type": "timeseries",
   "description": "Average percentage of the task’s offset commit attempts that succeeded\n",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(connector) (kafka_connect_connector_task_metrics_offset_commit_success_percentage*100\n)",
     "legendFormat": "{{connector}} (avg)"
    }
   ]
  },
  {
   "title": "Batch Size (avg/max)",
   "type": "timeseries",
   "description": "1) Maximum size of the batches processed by the connector\n2) ",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(connector) (kafka_connect_connector_task_metrics_batch_size_avg)\n",
     "legendFormat": "{{connector}} (avg)"
    },
    {
     "expr": "avg by(connector) (kafka_connect_connector_task_metrics_batch_size_max)",
     "legendFormat": "{{connector}} (max)"
    }
   ]
  },
  { "title": "Connect (Source)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 } },
  {
   "title": "Record write rate by Connector",
   "type": "timeseries",
   "description": "After transformations are applied, this is the average per-second number of records output from the transformations and written to Kafka for the task belonging to the named source connector in the worker (excludes any records filtered out by the transformations)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(hostname) (kafka_connect_source_task_metrics_source_record_write_rate)",
     "legendFormat": "{{ connector }}"
    }
   ]
  },
  {
   "title": "Record write rate by Host",
   "type": "timeseries",
   "description": "After transformations are applied, this is the average per-second number of records output from the transformations and written to Kafka for the task belonging to the named source connector in the worker (excludes any records filtered out by the transformations)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(hostname) (kafka_connect_source_task_metrics_source_record_write_rate)",
     "legendFormat": "{{ connector }}"
    }
   ]
  },
  {
   "title": "Poll Batch Max/Avg Time",
   "type": "timeseries",
   "description": "1) Maximum time in milliseconds taken by this task to poll for a batch of source records\n2) Average time in milliseconds taken by this task to poll for a batch of source records",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(connector) (kafka_connect_source_task_metrics_poll_batch_avg_time_ms)",
     "legendFormat": "{{connector}} (avg)"
    },
    {
     "expr": "avg by(connector) (kafka_connect_source_task_metrics_poll_batch_max_time_ms)",
     "legendFormat": "{{connector}} (max)"
    }
   ]
  },
  {
   "title": "Active Count",
   "type": "timeseries",
   "description": "Most recent number of records polled by the task but not yet completely written to Kafka",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(connector) (kafka_connect_source_task_metrics_source_record_active_count)",
     "legendFormat": "{{ connector }} "
    },
    {
     "expr": "sum by(connector) (kafka_connect_source_task_metrics_source_record_active_count_max)",
     "legendFormat": "{{ connector }} (max)"
    }
   ]
  },
  {
   "title": "Connector (Sink) (Todo)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 164 },
   "collapsed": true
  },
  {
   "title": "Confluent ksqlDB Server (TODO)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 165 },
   "targets": [
    {}
   ]
  },
  {
   "title": "KSQL Metrics: Bytes Consumed",
   "type": "graph",
   "description": "Total number of bytes consumed.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 166 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"io_confluent_ksql_metrics_confluent_ksql_engine_query_stats_bytes_consumed_total\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "KSQL Metrics: Messages Consumed",
   "type": "graph",
   "description": "Messages consumed per second.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 166 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"io_confluent_ksql_metrics_confluent_ksql_engine_query_stats_messages_consumed_per_sec\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "KSQL Metrics: Messages Produced",
   "type": "graph",
   "description": "Messages produced per second.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 166 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"io_confluent_ksql_metrics_confluent_ksql_engine_query_stats_messages_produced_per_sec\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{ kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "KSQL Metrics: Active Queries",
   "type": "graph",
   "description": "Number of active queries.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 172 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"io_confluent_ksql_metrics_confluent_ksql_engine_query_stats_num_active_queries\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{ kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "KSQL Metrics: Idle Queries",
   "type": "graph",
   "description": "Number of idle queries.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 172 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"io_confluent_ksql_metrics_confluent_ksql_engine_query_stats_num_idle_queries\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "KSQL Metrics: Persistent Queries",
   "type": "graph",
   "description": "Number of persistent queries.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 172 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"io_confluent_ksql_metrics_confluent_ksql_engine_query_stats_num_persistent_queries\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": " {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Confluent Schema Registry (TODO)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 178 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Kafka Schema Registry servers",
   "type": "stat",
   "description": "Number of Kafka Schema Registry servers",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count({__name__=~\"schemaregistry_.*_jetty_metrics_connections_active\"})"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "description": "Total number of active TCP connections.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\"schemaregistry_.*_jetty_metrics_connections_active\"})"
    }
   ]
  },
  {
   "title": "Open Rate",
   "type": "stat",
   "description": "The average rate per second of opened TCP connections.",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg({__name__=~\"schemaregistry_.*_jetty_metrics_connections_opened_rate\"})"
    }
   ]
  },
  {
   "title": "Close Rate",
   "type": "stat",
   "description": "The average rate per second of closed TCP connections.",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg({__name__=~\"schemaregistry_.*_jetty_metrics_connections_closed_rate\"})"
    }
   ]
  },
  {
   "title": "Confluent ControlCenter (TODO)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 183 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Healthcheck Streams Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 184 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "confluent_controlcenter_healthcheck_streams_status\n",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}