# Password encoder secret required for Kafka clusters participating in cluster linking
# This secret is used to encrypt passwords stored in the cluster linking configuration
apiVersion: v1
kind: Secret
metadata:
  name: password-encoder-secret
type: Opaque
stringData:
  password-encoder.txt: "password=my-secret-encoder-password"

