apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: operator
  labels:
    app: keycloak
spec:
  type: ClusterIP
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 8443
      targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: operator
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:22.0.1
          args:
            - "start-dev"
            - "--import-realm"
            - "--https-protocols=TLSv1.2"
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
            - name: KC_HTTP_ACCESS_LOG_ENABLED
              value: "true"
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: "/etc/certs/tls.pem"
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: "/etc/certs/tls-key.pem"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: keycloak-volume
              mountPath: /opt/keycloak/data/import
            - name: public-key-volume
              mountPath: /opt/keycloak/keys
              readOnly: true
            - name: keycloak-certs
              mountPath: /etc/certs
      volumes:
        - name: keycloak-volume
          configMap:
            name: keycloak-configmap
        - name: keycloak-certs
          configMap:
            name: keycloak-certs
        - name: public-key-volume
          secret:
            secretName: keycloak-public-key
