apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-db-data
  namespace: oracle
  labels:
    app: oracle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi