apiVersion: v1
kind: Service
metadata:
  name: oracle-db
  namespace: oracle
  labels:
    app: oracle
spec:
  type: ClusterIP
  selector:
    app: oracle
  ports:
    - name: oracle
      port: 1521
      targetPort: 1521
      protocol: TCP
    - name: oracle-dbw
      port: 5500
      targetPort: 5500
      protocol: TCP


