---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kraftcontroller-sa
  namespace: central
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kraftcontroller-configmap-updater
  namespace: central
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["kraftcontroller-dynamic-quorum"]
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kraftcontroller-configmap-updater
  namespace: central
subjects:
- kind: ServiceAccount
  name: kraftcontroller-sa
  namespace: central
roleRef:
  kind: Role
  name: kraftcontroller-configmap-updater
  apiGroup: rbac.authorization.k8s.io
