{
 "title": "Confluent Platform MB",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "controller_type",
    "label": "ClusterType",
    "query": {
     "query": "label_values(platform_confluent_io_type)"
    }
   },
   {
    "name": "component_name",
    "label": "Component",
    "query": {
     "query": "label_values({namespace=\"$namespace\", confluent_platform=\"true\"}, app)"
    }
   },
   { "name": "ClusterLink_Name", "label": "ClusterLink_Name" }
  ]
 },
 "panels": [
  { "title": "ClusterLink", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "kafka_server_cluster_link_fetcher_metrics_io_time_ns_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_fetcher_metrics_io_time_ns_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_server_fetcherstats_oneminuterate_BytesPerSec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kafka_server_fetcherstats_oneminuterate{name=\"BytesPerSec\",link_name=~\"$ClusterLink_Name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_server_cluster_link_fetcher_metrics_request_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_fetcher_metrics_request_rate",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_server_fetcherlagmetrics_value_DeadThreadCount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "kafka_server_link_clusterlinkfetchermanager_value {name=\"DeadThreadCount\",link_name=~\"$ClusterLink_Name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_server_fetcherstats_oneminuterate_RequestsPerSec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "kafka_server_fetcherstats_oneminuterate{name=\"RequestsPerSec\",link_name=~\"$ClusterLink_Name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_server_cluster_link_metrics_mirror_partition_count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_metrics_mirror_partition_count",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "kafka_server_fetcherlagmetrics_value_ConsumerLag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "kafka_server_fetcherlagmetrics_value{name=\"ConsumerLag\",link_name=~\"$ClusterLink_Name\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "kafka_server_cluster_link_metrics_link_fetcher_count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_metrics_link_fetcher_count",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "kafka_server_link_clusterlinkfetchermanager_value_MaxLag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "kafka_server_link_clusterlinkfetchermanager_value{name=\"MaxLag\",link_name=~\"$ClusterLink_Name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_server_link_clusterlinkfetchermanager_value_TotalFetchRate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "kafka_server_link_clusterlinkfetchermanager_value{name=\"TotalFetchRate\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fetcher_metrics_incoming_byte_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_fetcher_metrics_incoming_byte_rate",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "io_confluent_caas_volumemetrics_used{app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"}",
     "legendFormat": "Used {{pod }}"
    },
    {
     "expr": "io_confluent_caas_volumemetrics_total{app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"}",
     "legendFormat": "Total {{pod}}"
    }
   ]
  },
  {
   "title": "Disk Usage (Percentage)",
   "type": "graph",
   "description": "Kafka Broker Pods Disk Usage",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "io_confluent_caas_volumemetrics_percentused{app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Availabe (Percentage)",
   "type": "graph",
   "description": "Kafka Broker Pods Disk Usage",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 61 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "io_confluent_caas_volumemetrics_percentavailable{app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU/Mem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "Aggregated Kafka Broker Pods CPU Usage",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{pod=~\"$component_name-(\\\\d+)\"}[5m])) by (pod)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "Kafka Broker Pods Memory Usage",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{pod=~\"$component_name-(\\\\d+)\"}) by (pod)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Brokers Online",
     "type": "stat",
     "description": "Number of Brokers Online",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kafka_server_replicamanager_value{name=\"LeaderCount\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"})"
      }
     ]
    },
    {
     "title": "Active Controllers",
     "type": "stat",
     "description": "Number of active controllers in the cluster.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum(kafka_controller_kafkacontroller_value{name=\"ActiveControllerCount\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"}))"
      }
     ]
    },
    {
     "title": "Unclean Leader Election Rate",
     "type": "stat",
     "description": "Unclean leader election rate",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_controller_controllerstats_oneminuterate{name=~\"UncleanLeaderElectionsPerSec\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"})"
      }
     ]
    },
    {
     "title": "Online Partitions",
     "type": "stat",
     "description": "Partitions that are online",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_server_replicamanager_value{name=~\"PartitionCount\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"})"
      }
     ]
    },
    {
     "title": "Under Replicated Partitions",
     "type": "stat",
     "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_server_replicamanager_value{name=~\"UnderReplicatedPartitions\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"})"
      }
     ]
    },
    {
     "title": "Offline Partitions Count",
     "type": "stat",
     "description": "Number of partitions that don’t have an active leader and are hence not writable or readable.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_server_replicamanager_value{name=~\"OfflineReplicaCount\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"})"
      }
     ]
    },
    {
     "title": "Byte Rate",
     "type": "graph",
     "description": "Byte Rate",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesInPerSec\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"})",
       "legendFormat": "Incoming Byte Rate"
      },
      {
       "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesOutPerSec\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"})",
       "legendFormat": "Outgoing Byte Rate"
      }
     ]
    },
    {
     "title": "Messages In Per Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=\"MessagesInPerSec\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"})",
       "legendFormat": "{{Messages In Per Second}}"
      }
     ]
    },
    {
     "title": "Request Handler Avg Idle Percent",
     "type": "graph",
     "description": "Request Handler Avg Idle Percent",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_kafkarequesthandlerpool_oneminuterate{name=~\"RequestHandlerAvgIdlePercent\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"}*100",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Produce Request Rate",
     "type": "graph",
     "description": "Produce Request Rate.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=\"TotalProduceRequestsPerSec\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"})",
       "legendFormat": "Total Produce Request Rate"
      },
      {
       "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=\"FailedProduceRequestsPerSec\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"})",
       "legendFormat": "Failed Produce Request Rate"
      }
     ]
    },
    {
     "title": "Fetch Request Rate",
     "type": "graph",
     "description": "Fetch Request Rate",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=~\"TotalFetchRequestsPerSec\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"})",
       "legendFormat": "Fetch Request Rate"
      },
      {
       "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=~\"FailedFetchRequestsPerSec\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"})",
       "legendFormat": "Failed Fetch Request Rate"
      }
     ]
    },
    {
     "title": "Network Processor Avg Idle Percent",
     "type": "graph",
     "description": "Network Processor Avg Idle Percent",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_network_socketserver_value{name=~\"NetworkProcessorAvgIdlePercent\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"}*100",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Zookeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Quorum Size",
     "type": "stat",
     "description": "Quorum Size of Zookeeper ensemble",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg({__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_quorumsize\",app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Alive Connections",
     "type": "stat",
     "description": "Number of Alive Connections",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum({__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_numaliveconnections\",app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Outstanding Requests",
     "type": "graph",
     "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_outstandingrequests\",app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"}  ",
       "legendFormat": "{{pod}}-{{name2}}"
      }
     ]
    },
    {
     "title": "Number of ZNodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg({__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_nodecount\",app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Number of Watchers",
     "type": "stat",
     "description": "Number of Watchers",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum({__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_watchcount\",app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Request Latency - Minimum",
     "type": "graph",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_minrequestlatency\",app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk Usage (txnlog)",
     "type": "graph",
     "description": "Zookeeper Disk Usage (txnlog)",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"txnlog-$component_name.*\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Request Latency - Maximum",
     "type": "graph",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_maxrequestlatency\",app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Request Latency - Average",
     "type": "graph",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_avgrequestlatency\",app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Connect/Replicator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of Connectors",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 180 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kafka_connect_connect_worker_metrics_connector_count{app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"})",
       "legendFormat": "{{ pod}}"
      }
     ]
    },
    {
     "title": "Connector Startup Success Total",
     "type": "stat",
     "description": "The total number of connector starts that succeeded.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 180 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kafka_connect_connect_worker_metrics_connector_startup_success_total{app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Connector Startup Failure Total",
     "type": "stat",
     "description": "The total number of connector starts that failed.",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 180 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kafka_connect_connect_worker_metrics_connector_startup_failure_total{app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Number of Tasks",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 180 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kafka_connect_connect_worker_metrics_task_count{app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Task Startup Success Total",
     "type": "stat",
     "description": "The total number of task starts that succeeded.",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 180 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kafka_connect_connect_worker_metrics_task_startup_success_total{app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Task Startup Failure Total",
     "type": "stat",
     "description": "The total number of task starts that failed.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 180 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kafka_connect_connect_worker_metrics_task_startup_failure_total{app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Connect Metrics: IO Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 184 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_metrics_io_ratio{app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Connect Metrics: Incoming Byte Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 184 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_metrics_incoming_byte_rate{app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Connect Metrics: Network IO Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 184 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_metrics_network_io_rate{app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent ksqlDB Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "KSQL Metrics: Bytes Consumed",
     "type": "graph",
     "description": "Total number of bytes consumed.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 138 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"io_confluent_ksql_metrics_confluent_ksql_engine_query_stats_bytes_consumed_total\",app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Messages Consumed",
     "type": "graph",
     "description": "Messages consumed per second.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 138 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"io_confluent_ksql_metrics_confluent_ksql_engine_query_stats_messages_consumed_per_sec\",app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Messages Produced",
     "type": "graph",
     "description": "Messages produced per second.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 138 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"io_confluent_ksql_metrics_confluent_ksql_engine_query_stats_messages_produced_per_sec\",app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"}",
       "legendFormat": "{{ pod}}"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Active Queries",
     "type": "graph",
     "description": "Number of active queries.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 144 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"io_confluent_ksql_metrics_confluent_ksql_engine_query_stats_num_active_queries\",app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"}",
       "legendFormat": "{{ pod}}"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Idle Queries",
     "type": "graph",
     "description": "Number of idle queries.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 144 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"io_confluent_ksql_metrics_confluent_ksql_engine_query_stats_num_idle_queries\",app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Persistent Queries",
     "type": "graph",
     "description": "Number of persistent queries.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 144 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"io_confluent_ksql_metrics_confluent_ksql_engine_query_stats_num_persistent_queries\",app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"}",
       "legendFormat": " {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Schema Registry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of Kafka Schema Registry servers",
     "type": "stat",
     "description": "Number of Kafka Schema Registry servers",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count({__name__=~\"schemaregistry_.*_jetty_metrics_connections_active\",app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "stat",
     "description": "Total number of active TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum({__name__=~\"schemaregistry_.*_jetty_metrics_connections_active\",app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Open Rate",
     "type": "stat",
     "description": "The average rate per second of opened TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg({__name__=~\"schemaregistry_.*_jetty_metrics_connections_opened_rate\",app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Close Rate",
     "type": "stat",
     "description": "The average rate per second of closed TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg({__name__=~\"schemaregistry_.*_jetty_metrics_connections_closed_rate\",app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent ControlCenter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Healthcheck Streams Status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 134 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "confluent_controlcenter_healthcheck_streams_status{namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}