{
 "title": "Confluent Platform Only Kraft",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "controller_type",
    "label": "ClusterType",
    "query": {
     "query": "label_values(platform_confluent_io_type)"
    }
   },
   {
    "name": "component_name",
    "label": "Component",
    "query": {
     "query": "label_values({namespace=\"$namespace\", confluent_platform=\"true\"}, app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Kraft", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ActiveBrokerCount",
   "type": "gauge",
   "description": "When using KRaft, the number of registered and unfenced brokers as observed by this controller.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_controller_kafkacontroller_value{name=\"ActiveBrokerCount\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"})",
     "legendFormat": "ActiveBrokerCount"
    }
   ]
  },
  {
   "title": "FencedBrokerCount",
   "type": "gauge",
   "description": "When using KRaft, the number of registered but fenced brokers as observed by this controller.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_value{name=\"FencedBrokerCount\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"})",
     "legendFormat": "FencedBrokerCount"
    }
   ]
  },
  {
   "title": "GlobalTopicCount",
   "type": "gauge",
   "description": "The number of all topics in the cluster as observed by this controller.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_value{name=\"GlobalTopicCount\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GlobalPartitionCount",
   "type": "gauge",
   "description": "The number of all partitions in the cluster as observed by this controller.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_value{name=\"GlobalPartitionCount\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ActiveControllerCount",
   "type": "gauge",
   "description": "The number of active controllers on this node. Valid values are ‘0’ or ‘1’.",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(kafka_controller_kafkacontroller_value{name=\"ActiveControllerCount\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ActiveBrokerCount",
   "type": "timeseries",
   "description": "When using KRaft, the number of registered and unfenced brokers as observed by this controller.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "count(kafka_controller_kafkacontroller_value{name=\"ActiveBrokerCount\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"})",
     "legendFormat": "ActiveBrokerCount"
    }
   ]
  },
  {
   "title": "FencedBrokerCount",
   "type": "timeseries",
   "description": "When using KRaft, the number of registered but fenced brokers as observed by this controller.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_value{name=\"FencedBrokerCount\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"})",
     "legendFormat": "FencedBrokerCount"
    }
   ]
  },
  {
   "title": "LastCommittedRecordOffset",
   "type": "gauge",
   "description": "The active controller reports the offset of the last committed offset it consumed. \t\n\nInactive controllers will always report the same value as LastAppliedRecordOffset. You can monitor the last committed offsets to see that they are advancing. You can also use these metrics to check that all of the brokers and controllers are at a similar offset.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_value{name=\"LastCommittedRecordOffset\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "LastAppliedRecordOffset",
   "type": "gauge",
   "description": "Reports the offset of the last record applied by the controller.\n\nFor the active controller this may include uncommitted records. For the inactive controller this always includes committed records only.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_value{name=\"LastAppliedRecordOffset\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "LastAppliedRecordLagMs",
   "type": "timeseries",
   "description": "Reports the difference between the local time and the append time of the last applied record batch. \t\n\n\nFor active controllers the value of this lag is always zero.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_value{name=\"LastAppliedRecordLagMs\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "LastAppliedRecordTimestamp (epoch)",
   "type": "gauge",
   "description": "Reports the append time of the last applied record batch.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\nkafka_controller_kafkacontroller_value{name=\"LastAppliedRecordTimestamp\",namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk Usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "io_confluent_caas_volumemetrics_used{app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"}",
       "legendFormat": "Used {{pod }}"
      },
      {
       "expr": "io_confluent_caas_volumemetrics_total{app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"}",
       "legendFormat": "Total {{pod}}"
      }
     ]
    },
    {
     "title": "Disk Usage (Percentage)",
     "type": "graph",
     "description": "Kafka Broker Pods Disk Usage",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "io_confluent_caas_volumemetrics_percentused{app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk Availabe (Percentage)",
     "type": "graph",
     "description": "Kafka Broker Pods Disk Usage",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 85 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "io_confluent_caas_volumemetrics_percentavailable{app=~\"$component_name\", platform_confluent_io_type=~\"$controller_type\",namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU/Mem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "Aggregated Kafka Broker Pods CPU Usage",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 147 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{pod=~\"$component_name-(\\\\d+)\"}[5m])) by (pod)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "Kafka Broker Pods Memory Usage",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 147 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{pod=~\"$component_name-(\\\\d+)\"}) by (pod)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    }
   ]
  }
 ]
}