#!/bin/bash
# Pre-Setup: One-time environment setup for MRC ZK-to-KRaft Migration (Secured)
# Region 1 (central) -> my-cluster cluster
# Region 2 (east)    -> my-clusterdev cluster
#
# Security: TLS (secretRef for Kafka/KRaft, autoGeneratedCerts for ZK) + SASL/PLAIN + Digest (ZK) + RBAC with OAuth MDS (Keycloak)

set -e

# ============================================================
# Configuration — edit these for your environment
# ============================================================
REGION1_NS="${REGION1_NS:-central}"
REGION2_NS="${REGION2_NS:-east}"
REGION1_CONTEXT="${REGION1_CONTEXT:-<your-region1-k8s-context>}"
REGION2_CONTEXT="${REGION2_CONTEXT:-<your-region2-k8s-context>}"
PROJECT_ID="${PROJECT_ID:-<your-gcp-project>}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Operator image version
OPERATOR_VERSION="${OPERATOR_VERSION:-latest}"

# Domain for external access
DOMAIN="my-domain.example.com"

# Keycloak realm template (shared across playbooks)
# REALM_TEMPLATE: Provide your Keycloak realm JSON template

# Temp directory for generated certs
CERT_DIR="${SCRIPT_DIR}/.generated-certs"

# Sample credential files
# SAMPLES_DIR: Provide credential files for SASL/PLAIN

# ============================================================
# Colors + helpers
# ============================================================
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

print_step() { echo -e "\n${GREEN}==>${NC} $1"; }
echo_info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARN]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

run_cmd() {
    echo ""
    echo -e "${BLUE}  \$ $*${NC}"
    echo -en "${YELLOW}  Run? [Y/n]${NC} > "
    read -r REPLY
    if [[ $REPLY =~ ^[Nn]$ ]]; then
        echo_info "  Skipped."
        return 0
    fi
    "$@"
}

show_cmd() {
    echo -e "${BLUE}  \$ $*${NC}"
    "$@"
}

# Helpers: kubectl/helm scoped to each cluster
kube1() { kubectl --context "$REGION1_CONTEXT" "$@"; }
kube2() { kubectl --context "$REGION2_CONTEXT" "$@"; }
helm1() { helm --kube-context "$REGION1_CONTEXT" "$@"; }
helm2() { helm --kube-context "$REGION2_CONTEXT" "$@"; }

# ============================================================
# Banner
# ============================================================
echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  MRC ZK->KRaft Migration - Pre-Setup${NC}"
echo -e "${BLUE}  (True Multi-Cluster, Secured)${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "This script sets up the one-time prerequisites:"
echo "  1. Namespaces (one per cluster)"
echo "  2. TLS certificates (CA + component certs with wildcard SANs)"
echo "  3. Secrets (TLS, credentials, digest, MDS token, OAuth JAAS)"
echo "  4. Keycloak (OIDC identity provider for MDS OAuth)"
echo "  5. External-DNS (for LoadBalancer DNS sync)"
echo "  6. Confluent Operator (namespaced, one instance per cluster)"
echo ""
echo "Configuration:"
echo "  - Region 1: namespace=$REGION1_NS  cluster=$REGION1_CONTEXT"
echo "  - Region 2: namespace=$REGION2_NS  cluster=$REGION2_CONTEXT"
echo "  - GCP Project ID: $PROJECT_ID"
echo "  - Operator version: $OPERATOR_VERSION"
echo "  - Domain: $DOMAIN"
echo ""

# ============================================================
# Step 0: Verify Cluster Connectivity
# ============================================================
print_step "Step 0: Verify Cluster Connectivity"
echo "Checking region 1 cluster (my-cluster)..."
if ! kube1 cluster-info --request-timeout=5s &>/dev/null; then
    print_error "Cannot reach region 1 cluster: $REGION1_CONTEXT"
    echo "Run: gcloud container clusters get-credentials my-cluster --region=us-central1 --project=$PROJECT_ID"
    exit 1
fi
echo_info "Region 1 cluster reachable"

echo "Checking region 2 cluster (my-clusterdev)..."
if ! kube2 cluster-info --request-timeout=5s &>/dev/null; then
    print_error "Cannot reach region 2 cluster: $REGION2_CONTEXT"
    echo "Run: gcloud container clusters get-credentials my-clusterdev --region=us-east4  --project=$PROJECT_ID"
    exit 1
fi
echo_info "Region 2 cluster reachable"

# ============================================================
# Step 1: Create Namespaces
# ============================================================
print_step "Step 1: Create Namespaces"
echo "Region 1: namespace '$REGION1_NS' on my-cluster"
echo "Region 2: namespace '$REGION2_NS' on my-clusterdev"

run_cmd bash -c "kubectl --context '$REGION1_CONTEXT' create namespace '$REGION1_NS' --dry-run=client -o yaml | kubectl --context '$REGION1_CONTEXT' apply -f -"
run_cmd bash -c "kubectl --context '$REGION2_CONTEXT' create namespace '$REGION2_NS' --dry-run=client -o yaml | kubectl --context '$REGION2_CONTEXT' apply -f -"

# ============================================================
# Step 2: Generate TLS Certificates
# ============================================================
print_step "Step 2: Generate TLS Certificates"
echo "Generating CA and component certs with wildcard SANs for:"
echo "  - *.${DOMAIN} (external LoadBalancer DNS)"
echo "  - *.${REGION1_NS}.svc.cluster.local (region 1 internal)"
echo "  - *.${REGION2_NS}.svc.cluster.local (region 2 internal)"
echo "  - *.svc.cluster.local, localhost"
echo ""

if [[ -d "$CERT_DIR" && -f "$CERT_DIR/ca-cert.pem" ]]; then
    echo_info "Certificates already exist in $CERT_DIR (skipping generation)"
    echo_info "Delete $CERT_DIR to regenerate."
else
    run_cmd bash -c "
    mkdir -p '$CERT_DIR'
    cd '$CERT_DIR'

    echo_info() { echo -e '${GREEN}[INFO]${NC} \$1'; }

    # --- Generate CA ---
    echo_info 'Generating CA key and certificate...'
    openssl req -new -nodes -x509 -days 3650 \
        -keyout ca-key.pem \
        -out ca-cert.pem \
        -subj '/C=US/ST=California/L=PaloAlto/O=Confluent/OU=Engineering/CN=TestCA'

    # --- Generate component certificate (shared across KRaft, Kafka, ZK) ---
    echo_info 'Generating component key and CSR...'
    cat > san.cnf <<SANEOF
[req]
default_bits = 2048
prompt = no
default_md = sha256
distinguished_name = dn
req_extensions = v3_req

[dn]
C = US
ST = California
L = PaloAlto
O = Confluent
OU = Engineering
CN = kafka

[v3_req]
subjectAltName = @alt_names

[alt_names]
DNS.1 = *.${DOMAIN}
DNS.2 = *.${REGION1_NS}.svc.cluster.local
DNS.3 = *.${REGION2_NS}.svc.cluster.local
DNS.4 = *.svc.cluster.local
DNS.5 = *.cluster.local
DNS.6 = localhost
DNS.7 = *.kafka.${REGION1_NS}.svc.cluster.local
DNS.8 = *.kafka.${REGION2_NS}.svc.cluster.local
DNS.9 = *.kraftcontroller.${REGION1_NS}.svc.cluster.local
DNS.10 = *.kraftcontroller.${REGION2_NS}.svc.cluster.local
DNS.11 = kafka.${REGION1_NS}.svc.cluster.local
DNS.12 = kafka.${REGION2_NS}.svc.cluster.local
DNS.13 = kraftcontroller.${REGION1_NS}.svc.cluster.local
DNS.14 = kraftcontroller.${REGION2_NS}.svc.cluster.local
DNS.15 = *.zookeeper.${REGION1_NS}.svc.cluster.local
DNS.16 = *.zookeeper.${REGION2_NS}.svc.cluster.local
DNS.17 = zookeeper.${REGION1_NS}.svc.cluster.local
DNS.18 = zookeeper.${REGION2_NS}.svc.cluster.local
SANEOF

    openssl req -new -nodes \
        -keyout component-key.pem \
        -out component.csr \
        -config san.cnf

    echo_info 'Signing component certificate with CA...'
    openssl x509 -req -days 3650 \
        -in component.csr \
        -CA ca-cert.pem \
        -CAkey ca-key.pem \
        -CAcreateserial \
        -out component-cert.pem \
        -extensions v3_req \
        -extfile san.cnf

    # --- Create fullchain (cert + CA) ---
    cat component-cert.pem ca-cert.pem > fullchain.pem

    echo_info 'Certificates generated in $CERT_DIR'
    echo_info 'Files: ca-cert.pem, ca-key.pem, component-cert.pem, component-key.pem, fullchain.pem'
    "
fi

# ============================================================
# Step 3: Create TLS Secrets
# ============================================================
print_step "Step 3: Create TLS Secrets"
echo "Creating TLS secrets for KRaftController and Kafka in both regions."
echo "Secrets use: fullchain.pem (cert chain), privkey.pem (private key), cacerts.pem (CA cert)"

create_tls_secret() {
    local secret_name="$1"
    local namespace="$2"
    local kube_fn="$3"

    if $kube_fn get secret "$secret_name" -n "$namespace" &>/dev/null; then
        echo_info "$secret_name already exists in $namespace (skipping)"
    else
        echo_info "Creating $secret_name in $namespace..."
        run_cmd $kube_fn create secret generic "$secret_name" \
            --from-file=fullchain.pem="$CERT_DIR/fullchain.pem" \
            --from-file=privkey.pem="$CERT_DIR/component-key.pem" \
            --from-file=cacerts.pem="$CERT_DIR/ca-cert.pem" \
            -n "$namespace"
    fi
}

# KRaft controller TLS secrets
create_tls_secret "tls-kraftcontroller" "$REGION1_NS" "kube1"
create_tls_secret "tls-kraftcontroller" "$REGION2_NS" "kube2"

# Kafka TLS secrets
create_tls_secret "tls-kafka" "$REGION1_NS" "kube1"
create_tls_secret "tls-kafka" "$REGION2_NS" "kube2"

# ZooKeeper TLS secrets
create_tls_secret "tls-zookeeper" "$REGION1_NS" "kube1"
create_tls_secret "tls-zookeeper" "$REGION2_NS" "kube2"

# ============================================================
# Step 4: Create Credential Secrets (SASL/PLAIN + Digest)
# ============================================================
print_step "Step 4: Create Credential Secrets"
echo "Creating SASL/PLAIN + Digest credential secrets."
echo ""
echo "Credential files:"
echo "  - plain.txt:            client credentials (username=kafka, password=kafka-secret)"
echo "  - plain-users.json:     server-side user list for SASL/PLAIN"
echo "  - plain-interbroker.txt:                              inter-controller/inter-broker SASL credentials"
echo "  - kafka-server-listener-internal-plain-metrics.txt:  metrics reporter SASL credentials"
echo "  - digest.txt:           ZooKeeper digest credentials"
echo "  - digest-users.json:    ZooKeeper server-side digest user list"

create_credential_secret() {
    local namespace="$1"
    local kube_fn="$2"

    if $kube_fn get secret credential -n "$namespace" &>/dev/null; then
        echo_info "credential already exists in $namespace (skipping)"
    else
        # Create digest credential files inline
        local DIGEST_FILE
        DIGEST_FILE=$(mktemp)
        cat > "$DIGEST_FILE" <<'EOF'
username=kafka
password=kafka-secret
EOF
        local DIGEST_USERS_FILE
        DIGEST_USERS_FILE=$(mktemp)
        cat > "$DIGEST_USERS_FILE" <<'EOF'
{
  "kafka": "kafka-secret",
  "test": "test-secret"
}
EOF

        echo_info "Creating credential in $namespace..."
        run_cmd $kube_fn create secret generic credential \
            --from-file=plain.txt="$SAMPLES_DIR/plain.txt" \
            --from-file=plain-users.json="$SAMPLES_DIR/plain-users.json" \
            --from-file=plain-interbroker.txt="$SAMPLES_DIR/plain.txt" \
            --from-file=kafka-server-listener-internal-plain-metrics.txt="$SAMPLES_DIR/plain.txt" \
            --from-file=digest.txt="$DIGEST_FILE" \
            --from-file=digest-users.json="$DIGEST_USERS_FILE" \
            -n "$namespace"
        rm -f "$DIGEST_FILE" "$DIGEST_USERS_FILE"
    fi
}

create_credential_secret "$REGION1_NS" "kube1"
create_credential_secret "$REGION2_NS" "kube2"

# ============================================================
# Step 5: Create MDS Token Keypair Secret
# ============================================================
print_step "Step 5: Create MDS Token Keypair Secret"
echo "MDS uses RSA keypair for signing/verifying authorization tokens."

create_mds_token_secret() {
    local namespace="$1"
    local kube_fn="$2"

    if $kube_fn get secret mds-token -n "$namespace" &>/dev/null; then
        echo_info "mds-token already exists in $namespace (skipping)"
    else
        echo_info "Creating mds-token in $namespace..."
        run_cmd $kube_fn create secret generic mds-token \
            --from-file=mdsPublicKey.pem="$SAMPLES_DIR/mds-publickey.txt" \
            --from-file=mdsTokenKeyPair.pem="$SAMPLES_DIR/mds-tokenkeypair.txt" \
            -n "$namespace"
    fi
}

create_mds_token_secret "$REGION1_NS" "kube1"
create_mds_token_secret "$REGION2_NS" "kube2"

# ============================================================
# Step 6: Create OAuth JAAS Secret
# ============================================================
print_step "Step 6: Create OAuth JAAS Secret"
echo "OAuth client credentials for Keycloak (used by ERP and KafkaRest dependency)."
echo "Client: ssologin / my-oauth-client-secret"

create_oauth_secret() {
    local namespace="$1"
    local kube_fn="$2"

    if $kube_fn get secret oauth-jass -n "$namespace" &>/dev/null; then
        echo_info "oauth-jass already exists in $namespace (skipping)"
    else
        echo_info "Creating oauth-jass in $namespace..."
        # Create oauth.txt inline with Keycloak client credentials
        local OAUTH_FILE
        OAUTH_FILE=$(mktemp)
        cat > "$OAUTH_FILE" <<'OAUTHEOF'
clientId=ssologin
clientSecret=my-oauth-client-secret
OAUTHEOF
        run_cmd $kube_fn create secret generic oauth-jass \
            --from-file=oauth.txt="$OAUTH_FILE" \
            -n "$namespace"
        rm -f "$OAUTH_FILE"
    fi
}

create_oauth_secret "$REGION1_NS" "kube1"
create_oauth_secret "$REGION2_NS" "kube2"

# ============================================================
# Step 7: Deploy Keycloak (OIDC Identity Provider)
# ============================================================
print_step "Step 7: Deploy Keycloak (Central Identity Provider)"
echo "Keycloak provides OAuth/OIDC identity resolution for MDS RBAC."
echo "Deployed ONCE in Region 1 (central) — both regions reference via LoadBalancer DNS."
echo "Endpoint: http://keycloak.${DOMAIN}:8080/realms/sso_test"
echo "Realm: sso_test | Client: ssologin"

if kube1 get deployment keycloak -n "$REGION1_NS" &>/dev/null; then
    echo_info "Keycloak already exists in $REGION1_NS on my-cluster (skipping)"
else
    # Create ConfigMap with realm JSON
    if ! kube1 get configmap keycloak-configmap -n "$REGION1_NS" &>/dev/null; then
        echo_info "Creating keycloak-configmap in $REGION1_NS..."
        run_cmd kube1 create configmap keycloak-configmap \
            --from-file=realm.json="$REALM_TEMPLATE" \
            -n "$REGION1_NS"
    fi

    echo_info "Deploying Keycloak in $REGION1_NS on my-cluster (LoadBalancer for cross-cluster access)..."
    run_cmd bash -c "sed 's/__NAMESPACE__/${REGION1_NS}/g' '${SCRIPT_DIR}/resources/keycloak.yaml' | kubectl --context '${REGION1_CONTEXT}' apply -f -"
    echo_info "Waiting for Keycloak to be ready..."
    run_cmd kube1 rollout status deployment/keycloak -n "$REGION1_NS" --timeout=180s

    echo_info "Keycloak exposed via LoadBalancer — external-dns will sync to keycloak.${DOMAIN}"
    echo_info "Wait for DNS to propagate before deploying Kafka with MDS."
fi

# ============================================================
# Step 8: Deploy External-DNS
# ============================================================
print_step "Step 8: Deploy External-DNS"
echo "External-DNS automatically syncs LoadBalancer IPs with GCP Cloud DNS."
echo "Handles DNS for ZK, KRaft controllers, and Kafka brokers."
echo "Each cluster needs its own external-dns deployment."

# Region 1 (my-cluster)
if kube1 get deployment external-dns -n "$REGION1_NS" &>/dev/null; then
    echo_info "external-dns already exists in $REGION1_NS on my-cluster (skipping)"
else
    echo_info "Deploying external-dns on my-cluster..."
    run_cmd bash -c "sed -e 's/__REGION1_NS__/${REGION1_NS}/g' -e 's/__PROJECT_ID__/${PROJECT_ID}/g' '${SCRIPT_DIR}/resources/external-dns-region1.yaml' | kubectl --context '${REGION1_CONTEXT}' apply -f -"
    echo_info "Waiting for external-dns on my-cluster..."
    run_cmd kube1 wait --for=condition=available --timeout=120s deployment/external-dns -n "$REGION1_NS"
fi

# Region 2 (my-clusterdev)
if kube2 get deployment external-dns -n "$REGION2_NS" &>/dev/null; then
    echo_info "external-dns already exists in $REGION2_NS on my-clusterdev (skipping)"
else
    echo_info "Deploying external-dns on my-clusterdev..."
    run_cmd bash -c "sed -e 's/__REGION2_NS__/${REGION2_NS}/g' -e 's/__PROJECT_ID__/${PROJECT_ID}/g' '${SCRIPT_DIR}/resources/external-dns-region2.yaml' | kubectl --context '${REGION2_CONTEXT}' apply -f -"
    echo_info "Waiting for external-dns on my-clusterdev..."
    run_cmd kube2 wait --for=condition=available --timeout=120s deployment/external-dns -n "$REGION2_NS"
fi

# ============================================================
# Step 9: Deploy Confluent Operator via Helm
# ============================================================
print_step "Step 9: Deploy Confluent Operator via Helm"
echo "Operator image: confluent-operator:${OPERATOR_VERSION}"
echo "Each cluster gets its own namespaced operator instance."

# Clean up stale ClusterRoles if needed
if kube1 get clusterrole confluent-operator &>/dev/null; then
    STALE_NS=$(kube1 get clusterrole confluent-operator \
        -o jsonpath='{.metadata.annotations.meta\.helm\.sh/release-namespace}' 2>/dev/null)
    if [[ "$STALE_NS" != "$REGION1_NS" ]]; then
        print_warning "Deleting stale ClusterRole 'confluent-operator' on my-cluster (owned by '$STALE_NS')"
        run_cmd kube1 delete clusterrole confluent-operator
        run_cmd kube1 delete clusterrolebinding confluent-operator 2>/dev/null || true
    fi
fi

if kube2 get clusterrole confluent-operator &>/dev/null; then
    STALE_NS=$(kube2 get clusterrole confluent-operator \
        -o jsonpath='{.metadata.annotations.meta\.helm\.sh/release-namespace}' 2>/dev/null)
    if [[ "$STALE_NS" != "$REGION2_NS" ]]; then
        print_warning "Deleting stale ClusterRole 'confluent-operator' on my-clusterdev (owned by '$STALE_NS')"
        run_cmd kube2 delete clusterrole confluent-operator
        run_cmd kube2 delete clusterrolebinding confluent-operator 2>/dev/null || true
    fi
fi

# Region 1 - my-cluster
echo_info "Installing operator in $REGION1_NS on my-cluster..."
run_cmd helm1 upgrade --install \
    -f  \
    confluent-operator confluentinc/confluent-for-kubernetes \
    --set image.tag="${OPERATOR_VERSION}" \
    --set name="confluent-operator-${REGION1_NS}" \
    --namespace "$REGION1_NS"

# Region 2 - my-clusterdev
echo_info "Installing operator in $REGION2_NS on my-clusterdev..."
run_cmd helm2 upgrade --install \
    -f  \
    confluent-operator confluentinc/confluent-for-kubernetes \
    --set image.tag="${OPERATOR_VERSION}" \
    --set name="confluent-operator-${REGION2_NS}" \
    --namespace "$REGION2_NS"

# ============================================================
# Step 10: Create Admin CLI Config
# ============================================================
print_step "Step 10: Create Admin CLI Config"
echo "Creates a ConfigMap with security properties for admin CLI tools."
echo "Mounted at /mnt/admin-config on KRaft pods."

ADMIN_PROPS=$(mktemp)
cat > "$ADMIN_PROPS" <<'EOF'
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka" password="kafka-secret";
ssl.truststore.location=/mnt/sslcerts/truststore.p12
ssl.truststore.password=mystorepassword
ssl.truststore.type=PKCS12
EOF

if ! kube1 get configmap kraft-admin-config -n "$REGION1_NS" &>/dev/null; then
    run_cmd kube1 create configmap kraft-admin-config --from-file=security.properties="$ADMIN_PROPS" -n "$REGION1_NS"
fi
if ! kube2 get configmap kraft-admin-config -n "$REGION2_NS" &>/dev/null; then
    run_cmd kube2 create configmap kraft-admin-config --from-file=security.properties="$ADMIN_PROPS" -n "$REGION2_NS"
fi
rm -f "$ADMIN_PROPS"

# ============================================================
# Done
# ============================================================
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Pre-Setup Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Clusters configured:"
echo "  Region 1: $REGION1_NS on my-cluster  ($REGION1_CONTEXT)"
echo "  Region 2: $REGION2_NS on my-clusterdev ($REGION2_CONTEXT)"
echo ""
echo "Security resources created:"
echo "  - TLS certs:    tls-kraftcontroller, tls-kafka (both regions)"
echo "  - CA pair:      ca-pair-sslcerts (for ZK autoGeneratedCerts)"
echo "  - Credentials:  credential (SASL/PLAIN + digest)"
echo "  - MDS token:    mds-token (RSA keypair)"
echo "  - OAuth JAAS:   oauth-jass (Keycloak client credentials)"
echo "  - Admin config: kraft-admin-config (mounted on KRaft pods at /mnt/admin-config)"
echo "  - Keycloak:     OIDC provider in region 1 (realm: sso_test)"
echo ""
echo "Next steps:"
echo "  1. Run the migration setup:"
echo "     ./setup.sh"
echo ""
