apiVersion: apps.cpc.platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: datagen-connector-ss
spec:
  connectClusterRef:
    name: connect-ss
  connectorConfigs:
    class: "io.confluent.kafka.connect.datagen.DatagenConnector"
    taskMax: 6
    configs:
      kafka.topic: "pageviews"
      quickstart: "pageviews"
      key.converter: "org.apache.kafka.connect.storage.StringConverter"
      value.converter: "org.apache.kafka.connect.json.JsonConverter"
      value.converter.schemas.enable: "false"
      max.interval: "100"
      iterations: "10000000"
