apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  annotations:
    platform.confluent.io/broker-id-offset: "20"
  name: kafka
  namespace: west
spec:
  authorization:
    superUsers:
      - User:kafka
    type: rbac
  configOverrides:
    server:
      - client.rack=us-west1
      - confluent.license.topic.replication.factor=3
      - replica.selector.class=org.apache.kafka.common.replica.RackAwareReplicaSelector
  dataVolumeCapacity: 10Gi
  dependencies:
    kafkaRest:
      authentication:
        bearer:
          secretRef: mds-client
        type: bearer
    zookeeper:
      authentication:
        jaasConfig:
          secretRef: credential
        type: digest
      endpoint: zk-central.platformops.dev.gcp.devel.cpdev.cloud:2182,zk-east.platformops.dev.gcp.devel.cpdev.cloud:2182,zookeeper.west.svc.cluster.local:2182/mrc
      tls:
        enabled: true
  image:
    application: confluentinc/cp-server:7.7.0
    init: confluentinc/confluent-init-container:2.9.0
  listeners:
    external:
      authentication:
        jaasConfig:
          secretRef: credential
        type: plain
      tls:
        enabled: true
      externalAccess:
        loadBalancer:
          bootstrapPrefix: kafka-west-ext
          brokerPrefix: kafka-west-ext
          domain: platformops.dev.gcp.devel.cpdev.cloud
        type: loadBalancer
    replication:
      authentication:
        jaasConfig:
          secretRef: credential
        type: plain
      tls:
        enabled: true
      externalAccess:
        loadBalancer:
          bootstrapPrefix: kafka-west
          brokerPrefix: kafka-west
          domain: platformops.dev.gcp.devel.cpdev.cloud
        type: loadBalancer
    internal:
      authentication:
        jaasConfig:
          secretRef: credential
        type: plain
      tls:
        enabled: true
  podTemplate:
    serviceAccountName: kafka
  rackAssignment:
    nodeLabels:
      - topology.kubernetes.io/region
  replicas: 2
  services:
    mds:
      externalAccess:
        type: loadBalancer
        loadBalancer:
          domain: platformops.dev.gcp.devel.cpdev.cloud
          prefix: mds-west
          advertisedURL:
            enabled: true
            prefix: mds-west
      provider:
        ldap:
          address: ldap://ldap-central.platformops.dev.gcp.devel.cpdev.cloud:389
          authentication:
            simple:
              secretRef: credential
            type: simple
          configurations:
            groupMemberAttribute: member
            groupMemberAttributePattern: CN=(.*),DC=test,DC=com
            groupNameAttribute: cn
            groupObjectClass: group
            groupSearchBase: dc=test,dc=com
            groupSearchScope: 1
            userMemberOfAttributePattern: CN=(.*),DC=test,DC=com
            userNameAttribute: cn
            userObjectClass: organizationalRole
            userSearchBase: dc=test,dc=com
            userSearchScope: 1
        type: ldap
      tls:
        enabled: true
      tokenKeyPair:
        secretRef: mds-token
  tls:
    autoGeneratedCerts: true
  metricReporter:
    enabled: true
    bootstrapEndpoint: kafka-west.platformops.dev.gcp.devel.cpdev.cloud:9072
    authentication:        
      jaasConfig:
        secretRef: metric-creds
      type: plain
    tls:
      enabled: true