apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: production-storage-class
provisioner: kubernetes.io/gce-pd
# provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer