apiVersion: v1
kind: ConfigMap
metadata:
  name: oracle-sample-data-config
  namespace: oracle
  labels:
    app: oracle
    component: sample-data
data:
  sample-data-setup.sh: |
    #!/bin/bash
    # Oracle Sample Data Setup for ${XSTREAM_SCHEMA}.${XSTREAM_TABLE}

    echo "=== Creating Sample Data (${XSTREAM_SCHEMA}.${XSTREAM_TABLE}) ==="
    echo "PDB: ${ORACLE_PDB}, Schema: ${XSTREAM_SCHEMA}, Table: ${XSTREAM_TABLE}"

    # Generate SQL file with variable substitution
    cat > ${HOME}/sample_data_${XSTREAM_SCHEMA}_${XSTREAM_TABLE}.sql << SQLEOF
    SET ECHO ON
    SET SERVEROUTPUT ON
    WHENEVER SQLERROR CONTINUE

    -- Switch to PDB for sample data creation
    ALTER SESSION SET CONTAINER = ${ORACLE_PDB};
    SET SERVEROUTPUT ON

    PROMPT === Creating Sample Schema in PDB ===
    -- Handle existing user gracefully
    DECLARE
      user_exists EXCEPTION;
      PRAGMA EXCEPTION_INIT(user_exists, -1920);
    BEGIN
      EXECUTE IMMEDIATE 'CREATE USER ${XSTREAM_SCHEMA} IDENTIFIED BY "${XSTREAM_SCHEMA_PWD}"
        DEFAULT TABLESPACE ${XSTREAM_TBS} TEMPORARY TABLESPACE TEMP';
      DBMS_OUTPUT.PUT_LINE('User ${XSTREAM_SCHEMA} created successfully');
    EXCEPTION
      WHEN user_exists THEN
        DBMS_OUTPUT.PUT_LINE('User ${XSTREAM_SCHEMA} already exists - continuing');
    END;
    /

    -- Grant privileges
    GRANT CONNECT, RESOURCE TO ${XSTREAM_SCHEMA};
    GRANT UNLIMITED TABLESPACE TO ${XSTREAM_SCHEMA};

    -- Set current schema instead of reconnecting
    ALTER SESSION SET CURRENT_SCHEMA = ${XSTREAM_SCHEMA};
    SET SERVEROUTPUT ON
    PROMPT === Creating Table: ${XSTREAM_TABLE} ===
    -- Create the table with error handling
    DECLARE
      table_exists EXCEPTION;
      PRAGMA EXCEPTION_INIT(table_exists, -955);
    BEGIN
      EXECUTE IMMEDIATE 'CREATE TABLE ${XSTREAM_TABLE} (
          employee_id NUMBER PRIMARY KEY,
          first_name VARCHAR2(50) NOT NULL,
          last_name VARCHAR2(50) NOT NULL,
          email VARCHAR2(100) UNIQUE NOT NULL,
          phone_number VARCHAR2(20),
          hire_date DATE DEFAULT SYSDATE,
          job_id VARCHAR2(10),
          salary NUMBER(8,2),
          commission_pct NUMBER(2,2),
          manager_id NUMBER,
          department_id NUMBER,
          created_date DATE DEFAULT SYSDATE,
          modified_date DATE DEFAULT SYSDATE
      )';
      DBMS_OUTPUT.PUT_LINE('Table ${XSTREAM_TABLE} created');
    EXCEPTION
      WHEN table_exists THEN
        DBMS_OUTPUT.PUT_LINE('Table ${XSTREAM_TABLE} already exists');
    END;
    /

    PROMPT === Configuring Supplemental Logging for CDC (${XSTREAM_TABLE}) ===
    -- Enable supplemental logging for CDC (handle if already exists)
    BEGIN
      EXECUTE IMMEDIATE 'ALTER TABLE ${XSTREAM_SCHEMA}.${XSTREAM_TABLE} ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS';
      DBMS_OUTPUT.PUT_LINE('Supplemental logging enabled for ${XSTREAM_SCHEMA}.${XSTREAM_TABLE}');
    EXCEPTION
      WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Supplemental logging already configured for ${XSTREAM_SCHEMA}.${XSTREAM_TABLE}');
    END;
    /

    PROMPT === Inserting Sample Data into ${XSTREAM_TABLE} ===
    -- Clear and insert sample data
    DELETE FROM ${XSTREAM_TABLE};

    INSERT INTO ${XSTREAM_TABLE} VALUES (1001, 'Alice', 'Johnson', 'alice.johnson@company.com', '+1-555-0201', SYSDATE-365, 'IT_PROG', 75000, NULL, 1003, 10, SYSDATE-365, SYSDATE-365);
    INSERT INTO ${XSTREAM_TABLE} VALUES (1002, 'Bob', 'Smith', 'bob.smith@company.com', '+1-555-0202', SYSDATE-300, 'SA_REP', 55000, 0.15, 1004, 20, SYSDATE-300, SYSDATE-300);
    INSERT INTO ${XSTREAM_TABLE} VALUES (1003, 'Carol', 'Davis', 'carol.davis@company.com', '+1-555-0203', SYSDATE-500, 'IT_MGR', 95000, NULL, NULL, 10, SYSDATE-500, SYSDATE-500);
    INSERT INTO ${XSTREAM_TABLE} VALUES (1004, 'David', 'Wilson', 'david.wilson@company.com', '+1-555-0204', SYSDATE-400, 'SA_MGR', 85000, NULL, NULL, 20, SYSDATE-400, SYSDATE-400);
    INSERT INTO ${XSTREAM_TABLE} VALUES (1005, 'Emma', 'Brown', 'emma.brown@company.com', '+1-555-0205', SYSDATE-250, 'FI_ACCOUNT', 60000, NULL, 1006, 30, SYSDATE-250, SYSDATE-250);

    COMMIT;

    PROMPT === Verification ===
    SELECT COUNT(*) as employee_count FROM ${XSTREAM_TABLE};

    PROMPT === Check table-level supplemental logging for ${XSTREAM_TABLE} ===
    SET LINESIZE 200;
    SELECT * FROM ALL_LOG_GROUPS 
      WHERE LOG_GROUP_TYPE = 'ALL COLUMN LOGGING'
      AND OWNER = '${XSTREAM_SCHEMA}'
      AND TABLE_NAME = '${XSTREAM_TABLE}';

    PROMPT === Sample Data Complete (${XSTREAM_SCHEMA}.${XSTREAM_TABLE}) Complete ===
    EXIT;
    SQLEOF

    # Execute the generated SQL
    sqlplus -S / as sysdba @${HOME}/sample_data_${XSTREAM_SCHEMA}_${XSTREAM_TABLE}.sql | tee ${HOME}/sample_data_${XSTREAM_SCHEMA}_${XSTREAM_TABLE}.log

    # Check if the SQL file was executed successfully
    if [ $? -ne 0 ]; then
      echo "=== Sample Data Setup Failed ==="
      exit 1
    fi

    echo "=== Sample Data Setup Complete (${XSTREAM_SCHEMA}.${XSTREAM_TABLE}) ==="