apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: usm-agent-monitor
  namespace: confluent
spec:
  selector:
    matchLabels:
      app: usm-agent
  podMetricsEndpoints:
    - port: monitoring
      path: /stats/prometheus
      interval: 30s
      basicAuth:
        username:
          name: usm-prometheus-creds
          key: username
        password:
          name: usm-prometheus-creds
          key: password
