apiVersion: platform.confluent.io/v1beta1
kind: KRaftMigrationJob
metadata:
  name: kraftmigrationjob
  namespace: central
  annotations:
    # Uncomment to trigger finalization (after dual-write testing and observer promotion)
    # platform.confluent.io/kraft-migration-trigger-finalize-to-kraft: "true"

    # Uncomment to rollback to ZooKeeper (if needed)
    # platform.confluent.io/kraft-migration-trigger-rollback-to-zk: "true"
spec:
  dependencies:
    kafka:
      name: kafka
      namespace: central
    zookeeper:
      name: zookeeper
      namespace: central
    kRaftController:
      name: kraftcontroller
      namespace: central
