# Private Kafka cluster (accepts connections only)
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: dest
spec:
  replicas: 3
  dataVolumeCapacity: 10Gi
  image:
    application: confluentinc/cp-server:7.9.0
    init: confluentinc/confluent-init-container:2.10.0
  
  configOverrides:
    server:
      - inter.broker.protocol.version=3.1
  
  tls:
    secretRef: tls-certs
  
  listeners:
    internal:
      authentication:
        type: plain
        jaasConfig:
          secretRef: credential
      tls:
        enabled: true
    external:
      authentication:
        type: plain
        jaasConfig:
          secretRef: credential
      tls:
        enabled: true
  
  passwordEncoder:
    secretRef: password-encoder-secret
  

