apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: east
  annotations:
    platform.confluent.io/zookeeper-myid-offset: "10"
spec:
  replicas: 2
  dataVolumeCapacity: 10Gi
  logVolumeCapacity: 10Gi
  image:
    application: confluentinc/cp-zookeeper:7.9.6
    init: confluentinc/confluent-init-container:3.3.0
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: platformops.dev.gcp.devel.cpdev.cloud
      advertisedURL:
        enabled: true
        prefix: zk-east
      prefix: zk-east
  authentication:
    jaasConfig:
      secretRef: credential
    type: digest
  tls:
    secretRef: tls-zk-east
  configOverrides:
    server:
      - "4lw.commands.whitelist=*"
  peers:
    - server.0=zk-central0.platformops.dev.gcp.devel.cpdev.cloud:2888:3888
    - server.10=zookeeper-0.zookeeper.east.svc.cluster.local:2888:3888
    - server.11=zookeeper-1.zookeeper.east.svc.cluster.local:2888:3888
    - server.20=zk-west0.platformops.dev.gcp.devel.cpdev.cloud:2888:3888
    - server.21=zk-west1.platformops.dev.gcp.devel.cpdev.cloud:2888:3888
