apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: dest-rest
  namespace: dest
spec:
  kafkaClusterRef:
    name: kafka
    namespace: dest
  kafkaRest:
    authentication:
      type: basic
      basic:
        secretRef: rest-credential
    tls:
      secretRef: tls-certs

