# Arbitrary cluster name; surfaces as k8s.cluster.name in Splunk
clusterName: k8s-cfk

# Tell the chart we're on AKS (helps with some defaults)
distribution: aks

splunkPlatform:
  endpoint: "https://Splunk-Endpoint:8088/services/collector"
  token: "Token from Splunk"
  index: "Index from Splunk"
  insecureSkipVerify: true  # TODO: fix server cert; only use in non-prod

logsCollection:
  containers:
    enabled: true  # collect container stdout/stderr logs
