apiVersion: v1
kind: Secret
metadata:
  name: kafka-client-config
  namespace: kraft-central
type: Opaque
data:
  kafka.properties: Ym9vdHN0cmFwLnNlcnZlcnM9a3JhZnQta2Fma2EtdnB2LWNlbnRyYWwtZXh0MS5wbGF0Zm9ybW9wcy5kZXYuZ2NwLmRldmVsLmNwZGV2LmNsb3VkOjkwOTIKc2VjdXJpdHkucHJvdG9jb2w9UExBSU5URVhU
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic
  namespace: kraft-central
spec:
  serviceName: elastic
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      containers:
        - name: elastic
          image: confluentinc/cp-kafka:latest
          command:
            - /bin/sh
            - -c
            - |
              kafka-producer-perf-test \
                --topic elastic-0  \
                --record-size 64 \
                --throughput 1 \
                --producer.config /mnt/kafka.properties \
                --num-records 230400 && sleep 10000
          volumeMounts:
            - name: kafka-properties
              mountPath: /mnt
              readOnly: true
          resources:
            requests:
              memory: 512Mi # 768Mi
              cpu: 500m # 1000m
      volumes:
        - name: kafka-properties # Create secret with name `kafka-client-config` with client configurations
          secret:
            secretName: kafka-client-config

